name: Feisty Devils KC
favicon: null
layout_spectrum: 0.90794
typography_spectrum: 0.35327670630067587
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff0048'
    - '#ffffff'
    - '#40405d'
    - '#d78ca1'
    - '#df4a5e'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
