name: Feisty Devils KC
favicon: null
layout_spectrum: 0.90794
typography_spectrum: 0.20157
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#f1772a'
    - '#5b5758'
    - '#ed1b24'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
