typography_spectrum: 0.20157
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#f1772a'
    - '#5b5758'
    - '#ed1b24'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.90794
analytics:
  google: null
  facebook: null
  twitter: null
logo: null
name: Feisty Devils KC
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Riding Like Hell to Fight MS
purpose: []
