name: Feisty Devils KC
favicon: null
layout_spectrum: 0.90794
typography_spectrum: 0.20157
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#760001'
    - '#ed1b24'
    - '#929699'
  brandStrength: 0
  lightness: 0.625
  saturation: 0
  rhythmicContrast: 0
purpose: []
