name: Feisty Devils KC
favicon: null
layout_spectrum: 0.19536249339580536
typography_spectrum: 0.35327670630067587
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5386175450403243
  lightness: 0.14058144949376583
  saturation: 0.791584629798308
  rhythmicContrast: 0.22967721754685044
purpose: []
