name: Feisty Devils KC
favicon: null
layout_spectrum: 0.19536249339580536
typography_spectrum: 0.35327670630067587
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#21212b'
    - '#ae9d95'
    - '#7c4637'
    - '#f9ebd1'
    - '#ff7168'
  brandStrength: 0.5386175450403243
  lightness: 0.375
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
